/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three';
import React, { JSX } from 'react';
import { useGLTF } from '@react-three/drei';
import { GLTF } from 'three-stdlib';
import { useThree } from '@react-three/fiber';

type GLTFResult = GLTF & {
  nodes: {
    Diamond: THREE.Mesh;
    Diamond_1: THREE.Mesh;
  };
  materials: {
    Diamond: THREE.MeshPhysicalMaterial;
    Test: THREE.MeshStandardMaterial;
  };
};

export default function Model(props: JSX.IntrinsicElements['group']) {
  const { viewport } = useThree();
  const fit = Math.min(viewport.width, viewport.height);
  const padding = 0.8;

  const { nodes, materials } = useGLTF(
    '/models/diamond.glb'
  ) as unknown as GLTFResult;
  return (
    <group
      {...props}
      scale={fit * padding}
      position={[0, 0, 0]}
      dispose={null}
    >
      <group name='Scene'>
        <group name='Diamante'>
          <mesh
            name='Diamond'
            castShadow
            receiveShadow
            geometry={nodes.Diamond.geometry}
            material={materials.Diamond}
          />
          <mesh
            name='Diamond_1'
            castShadow
            receiveShadow
            geometry={nodes.Diamond_1.geometry}
            material={materials.Test}
          />
          <group
            name='Vertex1'
            position={[-0.499, -0.065, 0.001]}
            rotation={[0, -Math.PI / 4, 0]}
            scale={0.1}
          />
          <group
            name='Vertex2'
            position={[-0.351, -0.065, 0.35]}
            rotation={[0, -Math.PI / 4, 0]}
            scale={0.1}
          />
          <group
            name='Vertex3'
            position={[0.001, -0.065, 0.499]}
            rotation={[0, -Math.PI / 4, 0]}
            scale={0.1}
          />
          <group
            name='Vertex4'
            position={[0.35, -0.065, 0.351]}
            rotation={[0, -Math.PI / 4, 0]}
            scale={0.1}
          />
          <group
            name='Vertex5'
            position={[0.499, -0.065, -0.001]}
            rotation={[0, -Math.PI / 4, 0]}
            scale={0.1}
          />
          <group
            name='Vertex6'
            position={[0.351, -0.065, -0.35]}
            rotation={[0, -Math.PI / 4, 0]}
            scale={0.1}
          />
          <group
            name='Vertex7'
            position={[-0.001, -0.065, -0.499]}
            rotation={[0, -Math.PI / 4, 0]}
            scale={0.1}
          />
          <group
            name='Vertex8'
            position={[-0.35, -0.065, -0.351]}
            rotation={[0, -Math.PI / 4, 0]}
            scale={0.1}
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload('/models/diamond.glb');
