/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three';
import React, { JSX } from 'react';
import { Center, MeshDiscardMaterial, MeshRefractionMaterial, MeshTransmissionMaterial, Text3D, useGLTF, Wireframe } from '@react-three/drei';
import { GLTF } from 'three-stdlib';
import { useThree } from '@react-three/fiber';
import { Leva, useControls } from 'leva';
import { useTheme } from 'next-themes';
import { darkForeground, lightForeground } from '@/lib/const';
import { darkBackground } from '@/lib/const';
import { lightBackground } from '@/lib/const';

type GLTFResult = GLTF & {
  nodes: {
    Diamond: THREE.Mesh;
    Diamond_1: THREE.Mesh;
  };
  materials: {
    Diamond: THREE.MeshPhysicalMaterial;
    Test: THREE.MeshStandardMaterial;
  };
};

const glassMaterialProps = {
  thickness: 0.7,
  roughness: 0.1,
  transmission: 1,
  ior: 1.1,
  chromaticAberration: 0.1,
  backside: true,
  color: '#CD8FE1',
  envMapIntensity: 1,
};

const materialProps = {
  transmission: 1,
  thickness: 0.23,
  roughness: 0.21,
  chromaticAberration: 0.04,
  anisotropicBlur: 0.14,
  distortion: 0.16,
  distortionScale: 0.5,
  temporalDistortion: 0.2,
  transmissionSampler: true,
  backside: false,
  color: '#2e2e2e',
};

export default function Model(props: JSX.IntrinsicElements['group']) {
  const { viewport } = useThree();
  const fit = Math.min(viewport.width, viewport.height);
  const padding = 0.8;

  const { nodes, materials } = useGLTF(
    '/models/diamond.glb'
  ) as unknown as GLTFResult;
  const { resolvedTheme } = useTheme();

  const strokeColor = resolvedTheme === 'dark' ? darkForeground : lightForeground;

  const fillColor = resolvedTheme === 'dark' ? '#2e2e2e' : '#ffffff';
  
  const { materialType } = useControls('Material', {
    materialType: {
      options: ['Metallic', 'Glass'],
      value: 'Metallic', // Default to metallic
    },
  });

  // 2. Folder for Metallic props
  const metallicProps = useControls(
    'Metallic',
    {
      color: '#ffffff',
      metalness: { value: 1.0, min: 0, max: 1.0 },
      roughness: { value: 0.1, min: 0, max: 1.0 },
    },
    {
      // Only show this folder if 'Metallic' is selected
      render: (get) => get('Material.materialType') === 'Metallic',
    }
  );

  // 3. Folder for Glass (Transmission) props
  const glassProps = useControls(
    'Glass',
    {
      transmission: { value: 1.0, min: 0, max: 1.0 },
      thickness: { value: 0.5, min: 0, max: 5.0 },
      roughness: { value: 0.0, min: 0, max: 1.0 },
      chromaticAberration: { value: 0.03, min: 0, max: 0.2 },
      color: '#ffffff',
    },
    {
      // Only show this folder if 'Glass' is selected
      render: (get) => get('Material.materialType') === 'Glass',
    }
  );

  const textOffset = 0.02;

  return (
    <group {...props} scale={fit * padding} position={[0, 0, 0]} dispose={null}>
      <group name='Scene'>
        <group name='Diamante'>
          <mesh name='DiamondStroke' geometry={nodes.Diamond.geometry}>
            <meshStandardMaterial
              color={strokeColor}
              emissive={strokeColor}
              emissiveIntensity={2}
              toneMapped={false}
            />
          </mesh>
          <mesh
            name='DiamondFill'
            castShadow
            receiveShadow
            geometry={nodes.Diamond_1.geometry}
          >
            <MeshTransmissionMaterial {...materialProps} color={fillColor} />
          </mesh>
          <group
            name='Vertex1'
            position={[-0.499 - textOffset, -0.065, 0.001]}
            rotation={[0, -Math.PI / 2, 0]}
            scale={0.15}
          >
            <Center>
              <Text3D
                font='/fonts/BaseNeueBlack_Regular.json'
                size={0.15}
                height={0.05}
                letterSpacing={0.03}
                curveSegments={16}
                bevelSize={0.01}
                bevelThickness={0.01}
                bevelEnabled
              >
                FULLSTACK
                {/* --- DYNAMIC MATERIAL --- */}
                {/* We render the correct material based on the Leva dropdown */}
                {materialType === 'Metallic' && (
                  <meshStandardMaterial {...metallicProps} />
                )}
                {materialType === 'Glass' && (
                  <MeshTransmissionMaterial {...glassProps} />
                )}
              </Text3D>
            </Center>
          </group>
          <group
            name='Vertex2'
            position={[-0.351, -0.065, 0.35]}
            rotation={[0, -Math.PI / 4, 0]}
            scale={0.1}
          />
          <group
            name='Vertex3'
            position={[0.001, -0.065, 0.499]}
            rotation={[0, -Math.PI / 4, 0]}
            scale={0.1}
          />
          <group
            name='Vertex4'
            position={[0.35, -0.065, 0.351]}
            rotation={[0, -Math.PI / 4, 0]}
            scale={0.1}
          />
          <group
            name='Vertex5'
            position={[0.499, -0.065, -0.001]}
            rotation={[0, -Math.PI / 4, 0]}
            scale={0.1}
          />
          <group
            name='Vertex6'
            position={[0.351, -0.065, -0.35]}
            rotation={[0, -Math.PI / 4, 0]}
            scale={0.1}
          />
          <group
            name='Vertex7'
            position={[-0.001, -0.065, -0.499]}
            rotation={[0, -Math.PI / 4, 0]}
            scale={0.1}
          />
          <group
            name='Vertex8'
            position={[-0.35, -0.065, -0.351]}
            rotation={[0, -Math.PI / 4, 0]}
            scale={0.1}
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload('/models/diamond.glb');
