/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three';
import React, { JSX, useRef } from 'react';
import {
  Center,
  MeshTransmissionMaterial,
  Text3D,
  useGLTF,
} from '@react-three/drei';
import { GLTF } from 'three-stdlib';
import { useFrame, useThree } from '@react-three/fiber';
import { Leva, useControls } from 'leva';
import { useTheme } from 'next-themes';
import { darkForeground, lightForeground } from '@/lib/const';
import { easing } from 'maath';

type GLTFResult = GLTF & {
  nodes: {
    Diamond: THREE.Mesh;
    Diamond_1: THREE.Mesh;
  };
  materials: {
    Diamond: THREE.MeshPhysicalMaterial;
    Test: THREE.MeshStandardMaterial;
  };
};

const glassMaterialProps = {
  transmission: 1.0,
  thickness: 0.5,
  roughness: 0.0,
  chromaticAberration: 0.03,
  color: '#eca400',
};

const diamondMaterialProps = {
  transmission: 1,
  thickness: 0.23,
  roughness: 0.21,
  chromaticAberration: 0.04,
  anisotropicBlur: 0.14,
  distortion: 0.16,
  distortionScale: 0.5,
  temporalDistortion: 0.2,
  // transmissionSampler: true,
  backside: false,
  color: '#2e2e2e',
};

interface VertexPoint {
  position: [number, number, number];
  rotation: [number, number, number];
  scale: number;
  label: string;
}

const vertexPoints: VertexPoint[] = [
  {
    position: [-0.499, -0.065, 0.001],
    rotation: [0, 0, 0],
    scale: 0.15,
    label: 'FULLSTACK',
  },
  {
    position: [-0.351, -0.065, 0.35],
    rotation: [0, 0, 0],
    scale: 0.1,
    label: 'FRONTEND',
  },
  {
    position: [0.001, -0.065, 0.499],
    rotation: [0, 0, 0],
    scale: 0.1,
    label: 'BACKEND',
  },
  {
    position: [0.35, -0.065, 0.351],
    rotation: [0, -Math.PI / 4, 0],
    scale: 0.1,
    label: 'DEVOPS',
  },
  {
    position: [0.499, -0.065, -0.001],
    rotation: [0, 0, 0],
    scale: 0.1,
    label: 'DESIGN',
  },
  {
    position: [0.351, -0.065, -0.35],
    rotation: [0, 0, 0],
    scale: 0.1,
    label: 'MOBILE',
  },
  {
    position: [-0.001, -0.065, -0.499],
    rotation: [0, 0, 0],
    scale: 0.1,
    label: 'AI',
  },
  {
    position: [-0.35, -0.065, -0.351],
    rotation: [0, 0, 0],
    scale: 0.1,
    label: 'BLOCKCHAIN',
  },
];

const textOffset = 0.01;

export default function Model(props: JSX.IntrinsicElements['group']) {
  const { viewport } = useThree();
  const fit = Math.min(viewport.width, viewport.height);
  const padding = 0.8;

  const { nodes } = useGLTF('/models/diamond.glb') as unknown as GLTFResult;
  const { resolvedTheme } = useTheme();

  const strokeColor =
    resolvedTheme === 'dark' ? darkForeground : lightForeground;

  const fillColor = resolvedTheme === 'dark' ? '#2e2e2e' : '#ffffff';

  const scene = useRef<THREE.Group>(null!);

  useFrame((_) => {
    // rotation logic
    const r = scene.current.rotation;
    r.y += 0.0008;
  });

  return (
    <group
      {...props}
      ref={scene}
      scale={fit * padding}
      position={[-2, 0.3, 3]}
      dispose={null}
      name='Scene'
    >
      <group name='Diamante'>
        <mesh name='DiamondStroke' geometry={nodes.Diamond.geometry}>
          <meshStandardMaterial
            color={strokeColor}
            emissive={strokeColor}
            emissiveIntensity={2}
            toneMapped={false}
          />
        </mesh>
        <mesh
          name='DiamondFill'
          castShadow
          receiveShadow
          geometry={nodes.Diamond_1.geometry}
        >
          <MeshTransmissionMaterial
            {...diamondMaterialProps}
            color={fillColor}
          />
        </mesh>
        {vertexPoints.map((point, index) => {
          const { position, rotation, scale, label } = point;
          const yRotation = Math.atan2(position[0], position[2]);
          return (
            <group
              key={index}
              name={`Vertex${index + 1}`}
              position={[
                position[0] + textOffset * Math.sin(yRotation),
                position[1],
                position[2] + textOffset * Math.cos(yRotation),
              ]}
              rotation={[rotation[0], yRotation, rotation[2]]}
              scale={scale}
            >
              <Center>
                <Text3D
                  font='/fonts/BaseNeueBlack_Regular.json'
                  size={0.2}
                  height={0.05}
                  letterSpacing={0.03}
                  curveSegments={16}
                  bevelSize={0.01}
                  bevelThickness={0.01}
                  bevelEnabled
                >
                  {label}
                  <MeshTransmissionMaterial {...glassMaterialProps} />
                </Text3D>
              </Center>
            </group>
          );
        })}
        {/* <group>
          <Center>
            <Text3D
              font='/fonts/BaseNeueBlack_Regular.json'
              size={0.15}
              height={0.05}
              letterSpacing={0.03}
              curveSegments={16}
              bevelSize={0.01}
              bevelThickness={0.01}
              bevelEnabled
            >
              FULLSTACK
              <MeshTransmissionMaterial {...glassMaterialProps} />
            </Text3D>
          </Center>
        </group>
        <group
          name='Vertex2'
          position={[-0.351, -0.065, 0.35]}
          rotation={[0, -Math.PI / 4, 0]}
          scale={0.1}
        />
        <group
          name='Vertex3'
          position={[0.001, -0.065, 0.499]}
          rotation={[0, -Math.PI / 4, 0]}
          scale={0.1}
        />
        <group
          name='Vertex4'
          position={[0.35, -0.065, 0.351]}
          rotation={[0, -Math.PI / 4, 0]}
          scale={0.1}
        />
        <group
          name='Vertex5'
          position={[0.499, -0.065, -0.001]}
          rotation={[0, -Math.PI / 4, 0]}
          scale={0.1}
        />
        <group
          name='Vertex6'
          position={[0.351, -0.065, -0.35]}
          rotation={[0, -Math.PI / 4, 0]}
          scale={0.1}
        />
        <group
          name='Vertex7'
          position={[-0.001, -0.065, -0.499]}
          rotation={[0, -Math.PI / 4, 0]}
          scale={0.1}
        />
        <group
          name='Vertex8'
          position={[-0.35, -0.065, -0.351]}
          rotation={[0, -Math.PI / 4, 0]}
          scale={0.1}
        /> */}
      </group>
    </group>
  );
}

useGLTF.preload('/models/diamond.glb');
